name: Manual Update

env:
  TZ: Asia/Shanghai

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'target'
        required: true
        default: 'x-wrt'
      test:
        description: 'if test?'
        required: false
        default: 'false'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

    - name: Trigger update packages
      if: github.event.inputs.test != 'true'
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        event-type: Manual update packages for ${{ github.event.inputs.target }}
        client-payload: '{"target": "${{ github.event.inputs.target }}", "test": "false"}'

    - name: Trigger test
      if: github.event.inputs.test == 'true'
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        event-type: Test update packages for ${{ github.event.inputs.target }}
        client-payload: '{"target": "${{ github.event.inputs.target }}", "test": "true"}'

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 4