name: Repo Dispatcher

env:
  TZ: Asia/Shanghai

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'if test?'
        required: false
        default: 'false'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

    - name: Trigger update packages
      if: github.event.inputs.test != 'true'
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        event-type: Manual Update My Packages For X-WRT
        client-payload: '{"test": "false"}'

    - name: Trigger test
      if: github.event.inputs.test == 'true'
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        event-type: Test Update My Packages For X-WRT
        client-payload: '{"test": "true"}'

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 1
        keep_minimum_runs: 4