name: Update Checker

env:
  TZ: Asia/Shanghai

on:
  push:
    paths:
      - '.github/workflows/openwrt-packages.yml'
      - 'diy/**'
  schedule:
    - cron: 0 */12 * * *
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

    - name: Trigger update x-wrt packages
      run: |
        sudo timedatectl set-timezone "$TZ"
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
          -d '{"event_type": "Update Packages For X-Wrt", "client_payload": {"target": "x-wrt"}}'

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 4